### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by bryankanesr** [Project-Caruso/WUT#1]
Photos are not in proportion, aspect ratio is not the same when displayed. Pictures need to be square, as instagram pictures are displayed.

**Comment by jcaruso001** [comment]
As i indicated on the phone, bryan jr and I are working through this.

**Comment by BryanKaneJr** [comment]
![screenshot_2015-03-18-12-31-00](https://cloud.githubusercontent.com/assets/10835982/6713855/64efdcdc-cd6b-11e4-8a7f-02d0a0b64c59.png)

**Comment by BryanKaneJr** [comment]
Images are cropped too small, cutting off most of the image.

**Comment by bryankanesr** [comment]
How are we making out with the picture displaying and cropping issues?

**Comment by jcaruso001** [comment]
The new version now allows you to take the photo, select the area you want to upload and then preview the post before submitting it...

**Comment by jcaruso001** [comment]
Verified
