### ISSUE TITLE
Show like count in comments

### ISSUE THREAD

**Issue by jcaruso001** [Project-Caruso/WUT#12]
Can you roll into the current get comment response call the number of likes for the requested post?

**Comment by jcaruso001** [comment]
After that is done I need to update the comment list to add a header with the total number of likes.

**Comment by c-butcher** [comment]
When you call pull_feeds or pull_friends, the Post object should now have a field called 'likes'.

Tested on my localhost and it worked 100%, this needs to be verified on wut.mobi.

**Comment by jcaruso001** [comment]
Verified.
