### ISSUE TITLE
Trending (Total Posts)

### ISSUE THREAD

**Issue by bryankanesr** [Project-Caruso/WUT#2]
When on the Trending page, the total # of posts is too difficult to read. It is very small, cannot view with the white font on the grey circle. A transparent circle with a larger blue font would correct this and look much better. Or possibly a blue circle with the larger white bold font. We do not want a major font size increase, just a little larger so it's legible.

**Comment by jcaruso001** [comment]
I increased the for size by 2 and made the background blue.

This will be available in a later version (1.5), I have not pushed it yet.

![screenshot_2015-02-27-10-53-37](https://cloud.githubusercontent.com/assets/4194148/6416871/f5158444-be6e-11e4-9411-69340ad6b0f0.png)

**Comment by jcaruso001** [comment]
Corrected
