### ISSUE TITLE
Pulls - Trending Page

### ISSUE THREAD

**Issue by bryankanesr** [Project-Caruso/WUT#3]
When going back to the profile page the last post does not populate on its own. It's required to pull in order for the posts to populate. This is also the case after sharing a photo and checking it at the trending page. The photos do not populate, you have to pull to get them. This also failed several times, at one point I could not see any of the photos on the trending page. Only the comments were visible, no pictures.

**Comment by jcaruso001** [comment]
Your correct, it should refresh the list after "Share". I've put that in there... as for the photo's lets push out this version later and see if you still get it.

**Comment by jcaruso001** [comment]
I also added a "Stub" image to sit there until the real image is downloaded to your phone.

**Comment by jcaruso001** [comment]
Corrected.
