### ISSUE TITLE
Likes - not working

### ISSUE THREAD

**Issue by bryankanesr** [Project-Caruso/WUT#4]
When liking a picture, it is not in realtime. The like does not increase, it should move immediately as it does with all other social apps such as Facebook, Instagram etc...

**Comment by jcaruso001** [comment]
Yes, sorry this is another issue Bryan and I have been working on

**Comment by BryanKaneJr** [comment]
![screenshot_2015-03-18-12-31-07](https://cloud.githubusercontent.com/assets/10835982/6713845/54f0074e-cd6b-11e4-8b2c-5706d2d8a65f.png)

**Comment by BryanKaneJr** [comment]
Like button is cut off, and does not register the image has been liked when you press it.

**Comment by jcaruso001** [comment]
I was finally able to reproduce this on my old Samsung gal s4 and corrected the like button being cut off. and aligned so low.

**Comment by bryankanesr** [comment]
The likes are still not registering in realtime. Only the like cutoff issue has been resolved.

**Comment by jcaruso001** [comment]
This is fixed in the next version

**Comment by jcaruso001** [comment]
Verified.
