### ISSUE TITLE
Get Connections Feed

### ISSUE THREAD

**Issue by jcaruso001** [Project-Caruso/WUT#6]
Get Connections Feed Error

JSON response to Get Connections Feed: <br />
<b>Fatal error</b>:  Call to a member function get() on a non-object in <b>/home/wut/public_html/wut/wp-content/plugins/Whats-Up-Tonight/api/1/api.php</b> on line <b>737</b><br />
04-09 20:04:01.575: E/AndroidRuntime(28638): FATAL EXCEPTION: AsyncTask #4

**Comment by c-butcher** [comment]
Fixed this so that there is a [check to see if friend still exists before pulling feeds](https://github.com/Project-Caruso/Whats-Up-Tonight/commit/7dac955167ab92b44dfd5a3bb630559bf20f3b58)

**Comment by jcaruso001** [comment]
Verified.
